### ISSUE TITLE
RE: Plugin monokai-dark

### ISSUE THREAD

**Issue by napalmaftermath** [Theodus/micro-monokai-dark#2]
I get this error?

monokai-dark line:1(column:21) near '-':   parse error

**Comment by Theodus** [comment]
@napalmaftermath I have confirmed this on a fresh install of micro from source. It also occurs for the gotham-colors plugin. I suggest opening an issue on https://github.com/zyedidia/micro since it seems to be an issue with parsing the filename of the lua script.
